openapi: 3.0.3
info:
  title: My API
  version: '1.0'
  contact:
    name: Pete
    email: petri.niemi@sofigate.com
externalDocs:
  url: https://niemipt.github.io/testi-api/
servers:
  - url: https://httpbin.org
    description: HTTPBin palvelin
paths:
  /get:
    summary: HTTPBin GET
    description: HTTPBin GET resurssi
    get:
      responses:
        '200':
          description: Success
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/GetResponse'
  /post:
    summary: HTTPBin POST
    description: HTTPBIn POST resurssi
    post:
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/PostRequest'
            examples:
              '1':
                $ref: '#/components/examples/PostRequestExample1'
      responses:
        '200':
          description: Success
          content:
            'application/json':
              schema:
                type: object
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
      description: |-
        Example: 
        > Authorization: Basic ZGVtbzpwQDU1dzByZA==
  schemas:
    GetResponse:
      $ref: ./schemas/Responses.yaml#/GetResponse
    PostRequest:
      $ref: ./schemas/Requests.yaml#/PostRequest
  examples:
    PostRequestExample1:
      value:
        property1: arvo1
        property2: arvo2
security:
  - BasicAuth: []
