openapi: 3.0.3
info:
  title: My API
  version: '1.0'
  contact:
    name: Pete
    email: petri.niemi@sofigate.com
servers:
  - url: https://httpbin.org
    description: HTTPBin palvelin
paths:
  /get:
    summary: HTTPBin GET
    description: HTTPBin GET resurssi
    get:
      responses:
        '200':
          description: Success
          $ref: '#/components/schemas/GetResponse'
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
      description: |-
        Example: 
        > Authorization: Basic ZGVtbzpwQDU1dzByZA ==
  schemas:
    GetResponse:
      type: object
      properties:
        args:
          type: object
        headers:
          type: object
          properties:
            Accept:
              type: string
            Accept-Encoding:
              type: string
            Accept-Language:
              type: string
            Host:
              type: string
            Referer:
              type: string
              format: url
            User-Agent:
              type: string
            X-Amzn-Trace-Id:
              type: string
          additionalProperties: false
        origin:
          type: string
          format: ipv4
        url:
          type: string
          format: url
      additionalProperties: false
security:
  - BasicAuth: []
