openapi: 3.0.3
info:
  title: My API
  version: '1.0'
  contact:
    name: Pete
    email: petri.niemi@sofigate.com
externalDocs:
  url: "https://niemipt.github.io/testi-api/"
servers:
  - url: https://httpbin.org
    description: HTTPBin palvelin
paths:
  /get:
    summary: HTTPBin GET
    description: HTTPBin GET resurssi
    get:
      responses:
        '200':
          description: Success
          $ref: './schemas/GetResponse.yaml#/components/schemas/GetResponse'
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
      description: |-
        Example: 
        > Authorization: Basic ZGVtbzpwQDU1dzByZA==
security:
  - BasicAuth: []
